---
homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_installed_packages:
  - bash
  - chezmoi
  - git
  - gh
  - n
  - neovim
  - ripgrep
  - the_silver_searcher

homebrew_cask_apps:
  - 1password
  - bbedit
  - discord
  - firefox
  - google-chrome
  - google-drive
  - iina
  - kitty
  - microsoft-office
  - mullvadvpn
  - plex
  - postman
  - qbitorrent
  - rectangle
  - spotify
  - the_unarchiver
  - visual-studio-code

mas_email: andrewdchon@gmail.com
mas_signin_dialog: true
mas_upgrade_all_apps: true
mas_installed_apps:
  - { id: 869223134, name: 'KakaoTalk' }
  -
