---
# optional tasks
configure_osx: true

# Homebrew
homebrew_clear_cache: true
homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_installed_packages:
  - bash
  - chezmoi
  - git
  - gh
  - n
  - neovim
  - ripgrep
  - romkatv/powerlevel10k/powerlevel10k
  - the_silver_searcher
  - zsh-autosuggestions

homebrew_cask_apps:
  - 1password
  - discord
  - firefox
  - google-chrome
  - google-drive
  - iina
  - kitty
  - mullvadvpn
  - plex
  - postman
  - qbittorrent
  - rectangle
  - spotify
  - sublime-text
  - the-unarchiver
  - visual-studio-code

# MAS Mac Apps
mas_email: andrewdchon@gmail.com
mas_signin_dialog: true
mas_upgrade_all_apps: true
mas_uninstalled_apps: []
mas_installed_apps:
  - { id: 869223134, name: 'KakaoTalk' }
  - { id: 1451685025, name: 'WireGuard' }

# Dock
# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
  - Launchpad
  - TV
  - Podcasts
  - 'App Store'
  - Safari
  - Maps
  - Photos
  - FaceTime
  - Calendar
  - Contacts
  - Reminders
  - Notes
  - Music
  - News
  - 'System Preferences'

dockitems_persist:
  - name: Messages
    path: '/Applications/Messages.app/'
    pos: 2
  - name: Mail
    path: '/Applications/Mail.app/'
    pos: 3
  - name: '1Password 7'
    path: '/Applications/1Password 7.app/'
    pos: 4
  - name: 'Firefox'
    path: '/Applications/Firefox.app/'
    pos: 5
  - name: 'Spotify'
    path: '/Applications/Spotify.app/'
    pos: 6
  - name: 'Visual Studio Code'
    path: '/Applications/Visual Studio Code.app/'
    pos: 7
  - name: 'kitty'
    path: '/Applications/kitty.app/'
    pos: 8

# OSX Defaults
osx_script: "'{{ playbook_dir }}/tasks/.osx'"

# Extra packages
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
npm_packages:
  - name: '@fsouza/prettierd'
    state: latest
  - name: eslint_d
    state: latest
  - name: git-split-diffs
    state: latest
