---
# optional tasks
configure_osx: true

# Homebrew
homebrew_clear_cache: true
homebrew_taps:
  - homebrew/cask-fonts

homebrew_installed_packages:
  - chezmoi
  - git
  - go
  - neovim
  - node
  - romkatv/powerlevel10k/powerlevel10k
  - rust
  - zsh
  - zsh-autosuggestions

homebrew_cask_apps:
  - 1password
  - appcleaner
  - discord
  - firefox
  - font-jetbrains-mono-nerd-font
  - google-chrome
  - google-drive
  - iina
  - insomnia
  - mullvadvpn
  - obsidian
  - qbittorrent
  - rectangle
  - spotify
  - the-unarchiver
  - visual-studio-code
  - wezterm

# MAS Mac Apps
mas_email: andrewdchon@gmail.com
mas_signin_dialog: true
mas_upgrade_all_apps: true
mas_uninstalled_apps:
  - { id: 408981434, name: "iMovie" }
  - { id: 409183694, name: "Keynote" }
  - { id: 682658836, name: "GarageBand" }
mas_installed_apps:
  - { id: 869223134, name: "KakaoTalk" }
  - { id: 1502839586, name: "Hand Mirror" }
  - { id: 1475387142, name: "TailScale" }

# Dock
# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
  - Launchpad
  - TV
  - Podcasts
  - "App Store"
  - Safari
  - Maps
  - Photos
  - FaceTime
  - Calendar
  - Contacts
  - Reminders
  - Notes
  - Music
  - News
  - "System Settings"
  - Freeform

dockitems_persist:
  - name: Messages
    path: "/Applications/Messages.app/"
    pos: 2
  - name: Mail
    path: "/Applications/Mail.app/"
    pos: 3
  - name: 1Password
    path: "/Applications/1Password.app/"
    pos: 4
  - name: Firefox
    path: "/Applications/Firefox.app/"
    pos: 5
  - name: Spotify
    path: "/Applications/Spotify.app/"
    pos: 6
  - name: "Visual Studio Code"
    path: "/Applications/Visual Studio Code.app/"
    pos: 7
  - name: WezTerm
    path: "/Applications/WezTerm.app/"
    pos: 8
  - name: Discord
    path: "/Applications/Discord.app/"
    pos: 9

# OSX Defaults
osx_script: "'{{ playbook_dir }}/tasks/.osx'"

# Extra packages
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
npm_packages:
  - name: git-split-diffs
    state: latest
